feature: созданы тесты, обновлена логика сравнения
MihaMoor/Library pull request #17
Opened 2024-05-16 06:56 UTC by MihaMoor

Созданы тесты для Author и PublishingHouse.
Обновлена логика сравнения для PublishingHouse.
Удалены лишние крипты.

2024-05-17 01:54 UTC, Axerm commented on src/Book/Book.Domain/AggregatesModel/PublishingHouseAggregate/PublishingHouse.cs
> +    private IEnumerable<object> GetAuthorMatches(IEnumerable<Author> authors)
Возможно следует провести небольшой

2024-05-17 02:00 UTC, Axerm requested changes

2024-05-17 02:00 UTC, Axerm commented on src/Book/Book.Domain/AggregatesModel/PublishingHouseAggregate/PublishingHouse.cs
> +    private IEnumerable<object> GetAuthorMatches(IEnumerable<Author> authors)
Возможно стоит провести небольшой `investigation` и посмотреть в сторону каким ещё образом можно добиться подобного поведения. Как вариант использовать экземплярный метод списка `Intersect`, может есть более оптимальные способы.

2024-05-17 02:00 UTC, Axerm commented on src/Book/Book.UnitTests/DomainModels/AuthorTestData.cs
> +public class AuthorTestData
Может быть было бы лучше держать данные для тестов вместе с тестами.

2024-05-17 02:00 UTC, Axerm commented on src/Book/Book.UnitTests/DomainModels/PublishingHouseTestData.cs
Те же размышления.

2024-05-18 04:40 UTC, MihaMoor commented on src/Book/Book.Domain/AggregatesModel/PublishingHouseAggregate/PublishingHouse.cs
> +    private IEnumerable<object> GetAuthorMatches(IEnumerable<Author> authors)
Нашел внутренний метод сравнения коллекций))

2024-05-18 04:41 UTC, MihaMoor commented on src/Book/Book.UnitTests/DomainModels/AuthorTestData.cs
> +public class AuthorTestData
Разобрался с данными и как строятся тесты. Спасибо за пинок))

2024-05-18 05:23 UTC, Axerm approved these changes

2024-05-18 05:23 UTC, Axerm commented on src/Book/Book.UnitTests/DomainModels/AuthorTest.cs
Красивое)

2024-05-18 07:37 UTC, merged